### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jnbt/NBTInputStream

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#10]
INFO: Status: Saving configuration...
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/jnbt/NBTInputStream
        at pl.asiekierka.AsieLauncher.ServerListHandler.updateServerList(ServerListHandler.java:57)
        at pl.asiekierka.AsieLauncher.AsieLauncher.launch(AsieLauncher.java:345)
        at pl.asiekierka.AsieLauncher.LauncherThread.run(LauncherThread.java:18)
Caused by: java.lang.ClassNotFoundException: org.jnbt.NBTInputStream
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
Caused by: java.util.zip.ZipException: invalid code lengths set
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at sun.misc.Resource.getBytes(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        ... 9 more
Shutting down.

**Comment by acertain** [comment]
+1

**Comment by asiekierka** [comment]
adm-zip corrupts JAR files. node-zip corrupts PNG files in the JAR file.

node-archiver lacks features.

I'm going to need a while with this one.
