### ISSUE TITLE
beta8 does not like OptiFine

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#12]
INFO: Status: Repacking minecraft.jar...
java.util.zip.ZipException: invalid entry compressed size (expected 22627 but got 22690 bytes)
        at java.util.zip.ZipOutputStream.closeEntry(Unknown Source)
        at pl.asiekierka.AsieLauncher.Repacker.mergeJarFiles(Repacker.java:28)
        at pl.asiekierka.AsieLauncher.Repacker.merge(Repacker.java:60)
        at pl.asiekierka.AsieLauncher.Repacker.repackJar(Repacker.java:70)
        at pl.asiekierka.AsieLauncher.AsieLauncher.install(AsieLauncher.java:316)
        at pl.asiekierka.AsieLauncher.LauncherThread.run(LauncherThread.java:17)

This is on a 1.5.2 server. OptiFine was put in the jarPatches folder. This causes the client to never finish repacking the jar.

**Comment by asiekierka** [comment]
Despite the fact I'm not particularly fond of still supporting 1.5.2, I'll look into it later today or tomorrow.

**Comment by Gamoholic** [comment]
I would move to 1.6.2, but the mods are still too turbulent for me. I might start putting together a pack in a week or two.
