### ISSUE TITLE
Failing to generate info.json

### ISSUE THREAD

**Issue by precariouspanther** [asiekierka/asielauncher#15]
root@arcanum:/home/minecraft/asie# node also
[INFO] Checking for updates...
[INFO] Started ALSO 0.4.0-beta9
[INFO] [Launcher] Generating launcher JAR...
[INFO] Preparing directories
[INFO] Added directory mods
[INFO] Added directory texturepacks
[INFO] Added directory bin
[INFO] Added directory lib
[INFO] Ready - listening on port 8000!

fs.js:407
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './AsieLauncher/internal/info.json'
    at Object.fs.openSync (fs.js:407:18)
    at Object.fs.readFileSync (fs.js:273:15)
    at runHeartbeat (/home/minecraft/asie/AsieLauncher/internal/also.js:113:26)
    at Object.exports.run (/home/minecraft/asie/AsieLauncher/internal/also.js:205:3)
    at run (/home/minecraft/asie/also.js:16:7)
    at /home/minecraft/asie/also.js:25:4
    at /home/minecraft/asie/AsieLauncher/internal/updater.js:74:30
    at checkPackage (/home/minecraft/asie/AsieLauncher/internal/updater.js:49:9)
    at Request._callback (/home/minecraft/asie/AsieLauncher/internal/updater.js:74:4)
    at self.callback (/home/minecraft/asie/node_modules/request/request.js:129:22)

**Comment by precariouspanther** [comment]
Manually creating info.json in AsieLauncher/internal/ with the default content from the github repo ({"client_revision":150,"server_revision":200}) at least allows the server to continue. Should this be included in the server distribution?

**Comment by asiekierka** [comment]
The odd fact here is that the info.json was /not/ generated. I will look into it post-rc1.
