### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by notagain141** [asiekierka/asielauncher#23]
IT would be nice to be able to set where the launcher downloads and launches to/from

**Comment by Gamoholic** [comment]
Please explain why this would be helpful to you. You were having issues with a network drive, right?

**Comment by notagain141** [comment]
yes my home drive is a redirection to H:\ which is a mapping to a server volume and i get a permissions issues. however disregarding my direct issue i feel either it should be defaulting to appdata (like minecraft and other launchers i have used) or there should be the option to have the download go where the player wants rather than force them to use my documents.

I get the following error. (directory names changed for anonymity)
2013-10-14 05:31:30 [SEVERE] [ForgeModLoader] An error occurred trying to config
ure the minecraft home at \server\users\user.asielauncher\minecraftservername
 for Forge Mod Loader
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(Unknown Source)
        at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.ja
va:119)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.j
ava:90)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler
.java:67)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FML
LaunchHandler.java:34)
        at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTwea
ker.java:123)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2013-10-14 05:31:30 [SEVERE] [ForgeModLoader] Unable to launch
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(Unknown Source)
        at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.ja
va:119)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.j
ava:90)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler
.java:67)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FML
LaunchHandler.java:34)
        at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTwea
ker.java:123)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Shutting down.

if i copy the .asielauncher folder to appdata or anywhere on the local pc then hack around with the displayed Launching with arguments i can get it to work however this mean i am not using the launcher and i am not sure if that will continue to work due to the authentication session that is passed.
