### ISSUE TITLE
File Parser Error while using dev update

### ISSUE THREAD

**Issue by ghost** [asiekierka/asielauncher#30]
ReferenceError: name is not defined
    at getModInfo (/home/mopack/mcma/server/AsieLauncher/internal/fileParser.js:50:51)
    at /home/mopack/mcma/server/AsieLauncher/internal/fileParser.js:88:10
    at /home/mopack/mcma/server/AsieLauncher/internal/fileParser.js:25:4
    at Array.forEach (native)
    at Function._.each._.forEach (/home/mopack/mcma/server/node_modules/underscore/underscore.js:79:11)
    at /home/mopack/mcma/server/AsieLauncher/internal/fileParser.js:24:5
    at Array.forEach (native)
    at Function._.each._.forEach (/home/mopack/mcma/server/node_modules/underscore/underscore.js:79:11)
    at runList (/home/mopack/mcma/server/AsieLauncher/internal/fileParser.js:23:4)
    at Object.exports.getModList (/home/mopack/mcma/server/AsieLauncher/internal/fileParser.js:87:2)

I dont think i made any errors in the config?

**Comment by ghost** [comment]
Alright seemed to be fixed when I removed Tinker's Construct. I think their might be something messed up in the mcmod.info file

**Comment by ghost** [comment]
Fixed with SlimeKnights/TinkersConstruct@d4bfef708c117a01a3c701b9785e6e891a90219f

I think this probably was the same file parser error I had when using 0.4.1 rc, but it never crashed when using 0.4.1 rc branch.

**Comment by asiekierka** [comment]
Actually, no. I did a silent update about 15 minutes after you updated.
